"""
Seed country extras: income_level (World Bank), natural_resources, major_exports,
credit_rating_sp — all idempotent, only touches those 4 columns.

Run standalone:
    cd /root/metricshour/backend
    python -m app.seeders.country_extras

Or via seed.py --only country_extras
"""

import logging
import sys
import requests

from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session

sys.path.insert(0, "/root/metricshour/backend")

from app.database import SessionLocal
from app.models import Country

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

WORLD_BANK_URL = "https://api.worldbank.org/v2/country?format=json&per_page=500"

_INCOME_MAP = {
    "High income": "high",
    "Upper middle income": "upper_middle",
    "Lower middle income": "lower_middle",
    "Low income": "low",
    "Not classified": None,
}

# ---------------------------------------------------------------------------
# S&P sovereign credit ratings (as of early 2026)
# ---------------------------------------------------------------------------
CREDIT_RATINGS_SP: dict[str, str] = {
    # AAA
    "AU": "AAA",
    "AT": "AAA",
    "CA": "AAA",
    "DK": "AAA",
    "FI": "AAA",
    "DE": "AAA",
    "LU": "AAA",
    "NL": "AAA",
    "NO": "AAA",
    "SG": "AAA",
    "SE": "AAA",
    "CH": "AAA",
    # AA+
    "US": "AA+",
    "NZ": "AA+",
    "HK": "AA+",
    # AA
    "BE": "AA",
    "FR": "AA",
    "GB": "AA",
    "IE": "AA",
    # AA-
    "CZ": "AA-",
    "EE": "AA-",
    "IS": "AA-",
    "SK": "AA-",
    "SI": "AA-",
    "KR": "AA-",
    # A+
    "CN": "A+",
    "JP": "A+",
    "IL": "A+",
    "KW": "A+",
    "MY": "A+",
    "QA": "A+",
    "SA": "A+",
    "AE": "A+",
    "CL": "A+",
    # A
    "BH": "A",
    "KZ": "A",
    "MX": "A",
    "OM": "A",
    "PE": "A",
    "TW": "A+",
    # A-
    "HR": "A-",
    "HU": "A-",
    "IN": "BBB-",  # India is BBB- but listed under A- in brief — corrected below
    "IT": "BBB",   # corrected
    "LV": "A-",
    "LT": "A-",
    "MT": "A-",
    "PL": "A-",
    "PT": "BBB+",  # corrected
    # BBB+
    "BG": "BBB+",
    "CO": "BBB-",  # downgraded
    "ID": "BBB",
    "PH": "BBB+",
    "RO": "BBB-",
    "TH": "BBB+",
    "IN": "BBB-",
    "PT": "BBB+",
    "IT": "BBB",
    # BBB
    "AZ": "BB+",   # corrected
    "BO": "B+",    # downgraded
    "BR": "BB",
    "GE": "BB",
    "GT": "BB",
    "JM": "BB-",
    "MN": "B",
    "MA": "BB+",
    "NI": "B+",
    "PA": "BBB-",
    "PY": "BB",
    "TT": "BBB-",
    "UY": "BBB",
    # BBB-
    "BD": "BB+",   # upgraded recently
    "KH": "B+",
    "DO": "BB",
    "EC": "B-",
    "EG": "B-",
    "FJ": "B+",
    "RS": "BB+",
    "TR": "B+",
    # BB+
    "AM": "BB-",
    "AL": "B+",
    "BI": "NR",
    # BB
    "AR": "CCC+",  # Argentina has been distressed
    "CR": "B",
    "NG": "B-",
    "ZA": "BB-",
    # BB-
    "BA": "B",
    "CU": "NR",
    "GH": "CCC+",
    "KE": "B",
    # B+
    "BY": "NR",
    "CI": "BB-",
    "PK": "CCC+",
    "ZM": "SD",
    # B
    "AO": "B-",
    "CM": "B",
    "ET": "CCC",
    "GA": "B-",
    "MZ": "CCC+",
    "SN": "B+",
    "UG": "B+",
    "TZ": "B+",
    # B-
    "AF": "NR",
    "IQ": "B-",
    "SD": "NR",
    "SS": "NR",
    "VE": "SD",
    # CCC/other
    "YE": "NR",
    "SY": "NR",
    "LB": "SD",
    "ZW": "NR",
    "MM": "NR",
    "KP": "NR",
    # More comprehensive coverage
    "UA": "B",
    "RU": "NR",    # suspended/withdrawn after 2022
    "HR": "A-",
    "GR": "BBB-",
    "CY": "BBB+",
    "MK": "BB-",
    "ME": "B+",
    "MD": "B+",
    "LY": "NR",
    "IR": "NR",
    "UZ": "BB-",
    "TJ": "B-",
    "KG": "NR",
    "TM": "NR",
    "AZ": "BB+",
    "GE": "BB",
    "LA": "CCC+",
    "VN": "BB+",
    "MN": "B",
    "KH": "B+",
    "MM": "NR",
    "LK": "CCC+",
    "NP": "B+",
    "BT": "NR",
    "MV": "B+",
    "PG": "B+",
    "FJ": "B+",
    "SB": "NR",
    "VU": "NR",
    "WS": "NR",
    "TO": "NR",
    "KI": "NR",
    "TV": "NR",
    "NR": "NR",
    "PW": "NR",
    "MH": "NR",
    "FM": "NR",
    "TL": "NR",
    "BN": "NR",
    "NA": "BB",
    "BW": "BBB+",
    "ZA": "BB-",
    "MU": "Baa3",  # use Moody's proxy — correct S&P below
    "MU": "BB+",
    "SC": "B+",
    "RW": "B+",
    "KE": "B",
    "TZ": "B+",
    "UG": "B+",
    "MG": "B-",
    "MW": "NR",
    "ZM": "SD",
    "ZW": "NR",
    "MZ": "CCC+",
    "AO": "B-",
    "CM": "B",
    "GA": "B-",
    "GN": "B-",
    "GW": "NR",
    "SN": "B+",
    "ML": "NR",
    "BF": "CCC+",
    "NE": "NR",
    "TD": "NR",
    "CF": "NR",
    "ER": "NR",
    "SO": "NR",
    "DJ": "NR",
    "ET": "CCC",
    "TG": "B",
    "BJ": "B",
    "CI": "BB-",
    "GH": "CCC+",
    "NG": "B-",
    "SL": "NR",
    "LR": "NR",
    "GM": "NR",
    "CV": "B",
    "ST": "NR",
    "GQ": "NR",
    "CG": "B-",
    "SS": "NR",
    "BI": "NR",
    "HT": "NR",
    "JM": "BB-",
    "TT": "BBB-",
    "BB": "BB+",
    "BS": "BB-",
    "GY": "B+",
    "SR": "SD",
    "BZ": "B-",
    "GT": "BB",
    "HN": "BB-",
    "SV": "B-",
    "NI": "B+",
    "CR": "B",
    "PA": "BBB-",
    "JO": "BB-",
    "XK": "NR",
    "PS": "NR",
    "DZ": "NR",
    "TN": "CCC+",
    "LY": "NR",
    "EH": "NR",
    "MR": "NR",
}

# ---------------------------------------------------------------------------
# Natural resources (hardcoded, best-effort for ~160+ countries)
# ---------------------------------------------------------------------------
NATURAL_RESOURCES: dict[str, list[str]] = {
    "AF": ["natural gas", "petroleum", "coal", "copper", "gold", "iron ore", "lithium", "gemstones"],
    "AL": ["petroleum", "natural gas", "coal", "chromium", "copper", "iron ore", "nickel", "salt"],
    "DZ": ["petroleum", "natural gas", "iron ore", "phosphates", "uranium", "lead", "zinc"],
    "AO": ["petroleum", "diamonds", "iron ore", "phosphates", "copper", "gold", "bauxite"],
    "AR": ["petroleum", "natural gas", "lithium", "iron ore", "copper", "zinc", "gold", "silver", "arable land"],
    "AM": ["gold", "copper", "molybdenum", "zinc", "bauxite", "marble"],
    "AU": ["iron ore", "coal", "natural gas", "gold", "copper", "uranium", "nickel", "bauxite", "lithium"],
    "AT": ["iron ore", "oil", "timber", "magnesite", "lead", "coal", "lignite", "copper", "hydropower"],
    "AZ": ["petroleum", "natural gas", "iron ore", "nonferrous metals"],
    "BS": ["salt", "aragonite", "timber"],
    "BH": ["petroleum", "natural gas", "fish", "pearls"],
    "BD": ["natural gas", "arable land", "timber"],
    "BY": ["timber", "peat", "potash"],
    "BE": ["construction materials", "silica sand", "carbonates"],
    "BZ": ["arable land", "timber", "fish", "hydropower"],
    "BJ": ["petroleum", "cotton", "limestone", "marble"],
    "BT": ["timber", "hydropower", "gypsum", "calcium carbide"],
    "BO": ["natural gas", "tin", "zinc", "tungsten", "antimony", "silver", "iron ore", "lithium", "gold"],
    "BA": ["coal", "iron ore", "bauxite", "copper", "lead", "zinc", "cobalt", "manganese", "nickel"],
    "BW": ["diamonds", "copper", "nickel", "salt", "soda ash", "potash", "coal"],
    "BR": ["iron ore", "manganese", "bauxite", "nickel", "uranium", "gold", "petroleum", "hydropower", "timber"],
    "BN": ["petroleum", "natural gas", "timber"],
    "BG": ["bauxite", "copper", "lead", "zinc", "coal", "timber", "arable land"],
    "BF": ["gold", "manganese", "zinc", "limestone", "marble", "phosphates", "pumice"],
    "BI": ["nickel", "uranium", "rare earth oxides", "peat", "cobalt", "copper", "gold"],
    "KH": ["oil", "gas", "timber", "gemstones", "iron ore", "manganese", "phosphates", "hydropower"],
    "CM": ["petroleum", "bauxite", "iron ore", "timber", "hydropower"],
    "CA": ["iron ore", "nickel", "zinc", "copper", "gold", "lead", "uranium", "diamonds", "coal", "petroleum", "natural gas", "timber", "potash"],
    "CV": ["salt", "basalt", "limestone", "kaolin", "fish"],
    "CF": ["diamonds", "uranium", "timber", "gold", "oil", "hydropower"],
    "TD": ["petroleum", "uranium", "natron soda", "kaolin", "fish"],
    "CL": ["copper", "timber", "iron ore", "nitrates", "precious metals", "molybdenum", "lithium", "hydropower"],
    "CN": ["coal", "iron ore", "petroleum", "natural gas", "mercury", "tin", "tungsten", "antimony", "manganese", "molybdenum", "vanadium", "rare earth elements", "zinc", "uranium", "gold"],
    "CO": ["petroleum", "natural gas", "coal", "iron ore", "nickel", "gold", "copper", "emeralds", "hydropower"],
    "KM": ["arable land", "fish"],
    "CR": ["hydropower", "geothermal power", "timber", "fish"],
    "HR": ["oil", "coal", "bauxite", "iron ore", "calcium", "gypsum", "natural asphalt"],
    "CU": ["cobalt", "nickel", "iron ore", "chromium", "copper", "manganese", "silica", "salt", "timber"],
    "CY": ["copper", "pyrites", "asbestos", "gypsum", "timber", "salt", "marble"],
    "CZ": ["coal", "kaolin", "clay", "graphite", "timber"],
    "DK": ["petroleum", "natural gas", "fish", "salt", "limestone", "chalk"],
    "DJ": ["geothermal areas", "gold", "clay", "granite", "limestone", "marble", "salt", "diatomite"],
    "DM": ["timber", "hydropower", "arable land"],
    "DO": ["nickel", "bauxite", "gold", "silver", "arable land", "hydropower"],
    "EC": ["petroleum", "fish", "timber", "hydropower"],
    "EG": ["petroleum", "natural gas", "iron ore", "phosphates", "manganese", "limestone", "gypsum", "talc", "asbestos"],
    "SV": ["hydropower", "geothermal power", "petroleum", "arable land"],
    "GQ": ["petroleum", "natural gas", "timber", "gold"],
    "ER": ["gold", "potash", "zinc", "copper", "salt", "possibly oil"],
    "EE": ["oil shale", "peat", "phosphorite", "clay", "limestone", "sand", "dolomite", "arable land"],
    "SZ": ["asbestos", "coal", "clay", "cassiterite", "hydropower", "forests", "iron ore"],
    "ET": ["potash", "salt", "natural gas", "hydropower", "gold", "tantalum", "platinum"],
    "FJ": ["timber", "fish", "gold", "copper", "offshore oil"],
    "FI": ["timber", "iron ore", "copper", "zinc", "gold", "silver", "limestone"],
    "FR": ["coal", "iron ore", "bauxite", "zinc", "uranium", "antimony", "arsenic", "potash", "feldspar", "fluorspar", "gypsum", "timber"],
    "GA": ["petroleum", "manganese", "uranium", "gold", "timber", "iron ore"],
    "GM": ["fish", "clay", "silica sand", "titanium", "tin", "zircon"],
    "GE": ["timber", "hydropower", "manganese", "iron ore", "copper", "minor coal"],
    "DE": ["coal", "lignite", "natural gas", "iron ore", "copper", "nickel", "uranium", "potash", "salt", "construction materials", "timber", "arable land"],
    "GH": ["gold", "timber", "bauxite", "manganese", "fish", "rubber", "hydropower", "petroleum", "silver"],
    "GR": ["lignite", "petroleum", "iron ore", "bauxite", "lead", "zinc", "nickel", "magnesite", "marble", "salt"],
    "GL": ["coal", "iron ore", "lead", "zinc", "molybdenum", "rare earth elements", "gold", "platinum"],
    "GD": ["timber", "tropical fruit", "deepwater harbours"],
    "GT": ["petroleum", "nickel", "rare woods", "fish", "chicle", "hydropower"],
    "GN": ["bauxite", "iron ore", "diamonds", "gold", "uranium", "hydropower", "fish"],
    "GW": ["fish", "timber", "phosphates", "bauxite", "clay", "granite", "limestone"],
    "GY": ["bauxite", "gold", "diamonds", "hardwood timber", "shrimp", "fish", "petroleum"],
    "HT": ["bauxite", "copper", "calcium carbonate", "gold", "marble", "hydropower"],
    "HN": ["timber", "gold", "silver", "copper", "lead", "zinc", "iron ore", "antimony", "coal", "fish", "hydropower"],
    "HK": ["deepwater harbour"],
    "HU": ["bauxite", "coal", "natural gas", "arable land"],
    "IS": ["fish", "hydropower", "geothermal power", "diatomite"],
    "IN": ["coal", "iron ore", "manganese", "mica", "bauxite", "rare earth elements", "titanium ore", "chromite", "diamonds", "petroleum", "limestone", "arable land"],
    "ID": ["petroleum", "natural gas", "tin", "nickel", "timber", "bauxite", "copper", "coal", "gold", "silver"],
    "IR": ["petroleum", "natural gas", "coal", "chromium", "copper", "iron ore", "lead", "manganese", "zinc", "sulfur"],
    "IQ": ["petroleum", "natural gas", "phosphates", "sulfur"],
    "IE": ["natural gas", "peat", "copper", "lead", "zinc", "silver", "barite", "gypsum", "limestone", "dolomite"],
    "IL": ["timber", "potash", "copper ore", "natural gas", "phosphate rock", "magnesium bromide", "clays", "sand"],
    "IT": ["coal", "mercury", "zinc", "potash", "marble", "barite", "asbestos", "pumice", "fluorspar", "feldspar", "pyrite", "natural gas", "petroleum", "fish", "arable land"],
    "JM": ["bauxite", "gypsum", "limestone"],
    "JP": ["negligible mineral resources", "fish"],
    "JO": ["phosphates", "potash", "shale oil"],
    "KZ": ["petroleum", "natural gas", "coal", "iron ore", "manganese", "chrome", "nickel", "cobalt", "copper", "molybdenum", "lead", "zinc", "bauxite", "gold", "uranium"],
    "KE": ["tea", "coffee", "corn", "wheat", "sugarcane", "gold", "soda ash", "diatomite", "hydropower", "geothermal power"],
    "KI": ["phosphate", "fish"],
    "KW": ["petroleum", "fish", "shrimp", "natural gas"],
    "KG": ["gold", "rare earth metals", "mercury", "bismuth", "lead", "zinc", "hydropower"],
    "LA": ["timber", "hydropower", "gypsum", "tin", "gold", "gemstones"],
    "LV": ["peat", "limestone", "dolomite", "amber", "hydropower", "timber", "arable land"],
    "LB": ["limestone", "iron ore", "salt", "water"],
    "LS": ["water", "agricultural land", "diamonds"],
    "LR": ["iron ore", "timber", "diamonds", "gold", "hydropower"],
    "LY": ["petroleum", "natural gas", "gypsum"],
    "LT": ["peat", "arable land", "amber", "limestone", "clay", "sand"],
    "LU": ["iron ore"],
    "MG": ["graphite", "chromite", "coal", "bauxite", "rare earth elements", "salt", "quartz", "tar sands", "semiprecious stones"],
    "MW": ["limestone", "arable land", "hydropower", "uranium", "coal", "bauxite"],
    "MY": ["tin", "petroleum", "timber", "copper", "iron ore", "natural gas", "bauxite"],
    "MV": ["fish"],
    "ML": ["gold", "phosphates", "kaolin", "salt", "limestone", "uranium", "hydropower"],
    "MT": ["limestone", "salt", "arable land"],
    "MR": ["iron ore", "gypsum", "copper", "phosphate", "diamonds", "gold", "oil"],
    "MU": ["arable land", "fish"],
    "MX": ["petroleum", "silver", "copper", "gold", "zinc", "natural gas", "lead", "timber", "fish", "arable land"],
    "MD": ["lignite", "phosphorites", "gypsum", "limestone", "arable land"],
    "MN": ["oil", "coal", "copper", "molybdenum", "tungsten", "phosphates", "tin", "nickel", "zinc", "fluorspar", "gold", "silver", "iron"],
    "ME": ["bauxite", "hydroelectricity"],
    "MA": ["phosphates", "iron ore", "manganese", "lead", "zinc", "fish", "salt"],
    "MZ": ["coal", "titanium", "natural gas", "hydropower", "tantalum", "graphite"],
    "MM": ["petroleum", "timber", "tin", "antimony", "zinc", "copper", "tungsten", "lead", "coal", "marble", "limestone", "precious stones", "natural gas", "hydropower"],
    "NA": ["diamonds", "copper", "uranium", "gold", "silver", "lead", "tin", "lithium", "zinc", "salt", "hydropower", "fish"],
    "NP": ["quartz", "timber", "hydropower", "scenic beauty", "small deposits of lignite", "copper", "cobalt", "iron ore"],
    "NL": ["natural gas", "petroleum", "arable land", "peat"],
    "NZ": ["natural gas", "iron ore", "sand", "coal", "timber", "hydropower", "gold", "limestone"],
    "NI": ["gold", "silver", "copper", "tungsten", "lead", "zinc", "timber", "fish"],
    "NE": ["uranium", "coal", "iron ore", "tin", "phosphates", "gold", "petroleum"],
    "NG": ["petroleum", "tin", "iron ore", "coal", "limestone", "niobium", "lead", "zinc", "natural gas"],
    "KP": ["coal", "iron ore", "limestone", "magnesite", "graphite", "copper", "zinc", "lead", "precious metals"],
    "NO": ["petroleum", "natural gas", "iron ore", "copper", "zinc", "lead", "nickel", "titanium", "pyrites", "nickel", "fish", "timber", "hydropower"],
    "OM": ["petroleum", "copper", "asbestos", "marble", "limestone", "chromium", "gypsum", "natural gas"],
    "PK": ["land", "natural gas reserves", "limited petroleum", "poor quality coal", "iron ore", "copper", "salt", "limestone"],
    "PA": ["copper", "mahogany forests", "shrimp", "hydropower"],
    "PG": ["gold", "copper", "silver", "natural gas", "timber", "oil", "fisheries"],
    "PY": ["hydropower", "timber", "iron ore", "manganese", "limestone"],
    "PE": ["copper", "gold", "zinc", "silver", "lead", "oil", "natural gas", "timber", "fish", "iron ore", "phosphates"],
    "PH": ["timber", "petroleum", "nickel", "cobalt", "silver", "gold", "salt", "copper", "chromite"],
    "PL": ["coal", "sulfur", "copper", "natural gas", "silver", "lead", "salt", "amber", "arable land"],
    "PT": ["fish", "forests", "tungsten", "iron ore", "uranium ore", "marble", "lithium"],
    "QA": ["petroleum", "natural gas", "fish"],
    "RO": ["petroleum", "timber", "natural gas", "coal", "iron ore", "salt", "arable land", "hydropower"],
    "RU": ["major deposits of oil", "natural gas", "coal", "timber", "iron ore", "manganese", "chromium", "nickel", "platinum", "titanium", "copper", "tin", "lead", "tungsten", "diamonds", "phosphates", "gold", "rare earth elements"],
    "RW": ["gold", "cassiterite", "wolframite", "methane", "hydropower", "arable land"],
    "SA": ["petroleum", "natural gas", "iron ore", "gold", "copper"],
    "SN": ["fish", "phosphates", "iron ore", "zircon", "gold", "petroleum"],
    "RS": ["oil", "gas", "coal", "iron ore", "copper", "zinc", "antimony", "chromite", "gold", "silver", "magnesium", "pyrite", "limestone"],
    "SC": ["fish", "coconuts", "cinnamon trees", "vanilla"],
    "SL": ["diamonds", "titanium ore", "bauxite", "iron ore", "gold", "chromite"],
    "SG": ["fish", "deepwater port"],
    "SK": ["brown coal", "iron ore", "copper", "manganese", "salt"],
    "SI": ["lignite", "lead", "zinc", "building stone", "hydropower", "forests"],
    "SB": ["fish", "forests", "gold", "bauxite", "phosphates", "lead", "zinc"],
    "SO": ["uranium", "largely unexploited reserves of iron ore", "tin", "gypsum", "bauxite", "copper", "salt", "natural gas"],
    "ZA": ["gold", "chromium", "antimony", "coal", "iron ore", "manganese", "nickel", "phosphates", "tin", "rare earth elements", "uranium", "gem diamonds", "platinum", "copper", "vanadium", "salt"],
    "SS": ["hydropower", "fertile agricultural land", "gold", "diamonds", "petroleum", "hardwoods", "limestone", "iron ore", "copper", "chromium ore", "zinc", "tungsten", "mica", "silver"],
    "ES": ["coal", "lignite", "iron ore", "copper", "lead", "zinc", "uranium", "tungsten", "mercury", "pyrites", "magnesite", "fluorspar", "gypsum", "sepiolite", "kaolin", "potash", "hydropower", "arable land"],
    "LK": ["limestone", "graphite", "mineral sands", "gems", "phosphates", "clay", "hydropower"],
    "SD": ["petroleum", "small reserves of iron ore", "copper", "chromium ore", "zinc", "tungsten", "mica", "silver", "gold"],
    "SR": ["gold", "bauxite", "diamonds", "timber", "fish", "hydropower"],
    "SE": ["iron ore", "copper", "lead", "zinc", "gold", "silver", "tungsten", "uranium", "arsenic", "feldspar", "timber", "hydropower"],
    "CH": ["hydropower", "timber", "salt"],
    "SY": ["petroleum", "phosphates", "chrome and manganese ores", "asphalt", "iron ore", "rock salt", "marble", "gypsum", "hydropower"],
    "TW": ["small deposits of coal", "natural gas", "limestone", "marble", "asbestos"],
    "TJ": ["hydropower", "some petroleum", "uranium", "mercury", "brown coal", "lead", "zinc", "antimony", "tungsten", "silver", "gold"],
    "TZ": ["hydropower", "tin", "phosphates", "iron ore", "coal", "diamonds", "gemstones", "gold", "natural gas", "nickel"],
    "TH": ["tin", "rubber", "natural gas", "tungsten", "tantalum", "timber", "lead", "fish", "gypsum", "lignite", "fluorite", "arable land"],
    "TL": ["gold", "petroleum", "natural gas", "manganese", "marble"],
    "TG": ["phosphates", "limestone", "marble", "arable land"],
    "TO": ["fish", "fertile soil"],
    "TT": ["petroleum", "natural gas", "asphalt"],
    "TN": ["petroleum", "phosphates", "iron ore", "lead", "zinc", "salt"],
    "TR": ["coal", "iron ore", "copper", "chromium", "antimony", "mercury", "gold", "barite", "borate", "celestite", "emery", "feldspar", "limestone", "magnesite", "marble", "perlite", "pumice", "pyrites", "clay", "arable land", "hydropower"],
    "TM": ["petroleum", "natural gas", "sulfur", "salt"],
    "TV": ["fish"],
    "UG": ["copper", "cobalt", "hydropower", "limestone", "salt", "arable land", "gold"],
    "UA": ["iron ore", "coal", "manganese", "natural gas", "oil", "salt", "sulfur", "graphite", "titanium", "magnesium", "kaolin", "nickel", "mercury", "timber", "arable land"],
    "AE": ["petroleum", "natural gas"],
    "GB": ["coal", "petroleum", "natural gas", "iron ore", "lead", "zinc", "gold", "tin", "limestone", "salt", "clay", "chalk", "gypsum", "potash", "silica sand", "slate", "arable land"],
    "US": ["coal", "petroleum", "natural gas", "copper", "gold", "iron ore", "nickel", "phosphates", "potash", "silver", "uranium", "timber", "arable land"],
    "UY": ["arable land", "hydropower", "minor minerals"],
    "UZ": ["natural gas", "petroleum", "coal", "gold", "uranium", "silver", "copper", "lead", "zinc", "tungsten", "molybdenum"],
    "VU": ["manganese", "hardwood forests", "fish"],
    "VE": ["petroleum", "natural gas", "iron ore", "gold", "bauxite", "other minerals", "hydropower", "diamonds"],
    "VN": ["phosphates", "coal", "manganese", "rare earth elements", "bauxite", "chromate", "offshore oil", "gas deposits", "timber", "hydropower"],
    "YE": ["petroleum", "fish", "rock salt", "marble", "small deposits of coal", "gold", "lead", "nickel", "copper"],
    "ZM": ["copper", "cobalt", "zinc", "lead", "coal", "emeralds", "gold", "silver", "uranium", "hydropower"],
    "ZW": ["coal", "chromium ore", "asbestos", "gold", "nickel", "copper", "iron ore", "vanadium", "lithium", "tin", "platinum group metals"],
    "KZ": ["petroleum", "natural gas", "coal", "iron ore", "manganese", "chrome", "nickel", "cobalt", "copper", "molybdenum", "lead", "zinc", "bauxite", "gold", "uranium"],
    "MK": ["iron ore", "copper", "lead", "zinc", "chromium", "manganese", "nickel", "tungsten", "gold", "silver", "asbestos", "gypsum", "timber", "arable land"],
    "XK": ["nickel", "lead", "zinc", "chromite", "bauxite", "coal", "timber"],
    "CW": ["calcium phosphates"],
    "GI": ["none significant"],
    "IM": ["none significant"],
    "JE": ["none significant"],
    "GG": ["none significant"],
    "BM": ["none significant"],
    "KY": ["fish", "climate"],
    "TC": ["spiny lobster", "conch"],
    "AI": ["salt", "fish"],
    "MS": ["arable land"],
    "VG": ["none significant"],
    "AW": ["aloe", "fish"],
    "BQ": ["none significant"],
    "SX": ["none significant"],
    "MF": ["none significant"],
    "BL": ["none significant"],
    "PM": ["fish"],
    "GP": ["cultivable land", "beaches"],
    "MQ": ["cultivable land"],
    "GF": ["gold", "timber", "bauxite", "clay"],
    "RE": ["fish", "arable land"],
    "YT": ["arable land"],
    "NC": ["nickel", "iron", "cobalt", "manganese", "silver", "gold", "lead", "copper"],
    "PF": ["timber", "fish", "cobalt", "hydropower"],
    "TF": ["fish"],
    "CX": ["fish", "phosphate"],
    "CC": ["fish"],
    "NF": ["fish"],
    "NU": ["fish", "arable land"],
    "CK": ["copra", "citrus fruit", "fishing"],
    "WF": ["fish"],
    "TK": ["fish", "phosphate"],
    "PN": ["none significant"],
    "SH": ["fish"],
    "IO": ["fish"],
    "HM": ["none significant"],
    "BV": ["none significant"],
    "GS": ["fish"],
    "AQ": ["iron ore", "chromium", "copper", "gold", "nickel", "platinum"],
    "FK": ["fish", "squid", "wool"],
    "FO": ["fish", "whales"],
    "SJ": ["coal", "iron ore", "copper", "zinc", "phosphate", "wildlife", "scenic beauty"],
    "NR": ["phosphates", "fish"],
    "PW": ["forests", "minerals", "marine products", "deepwater seabed minerals"],
    "MH": ["coconut products", "marine products", "deep seabed minerals"],
    "KI": ["phosphate", "fish"],
    "SM": ["building stone"],
    "VA": ["none significant"],
    "AD": ["hydropower", "mineral water", "timber"],
    "MC": ["none significant"],
    "LI": ["hydroelectric potential", "arable land"],
    "GL": ["coal", "iron ore", "lead", "zinc", "molybdenum", "rare earth elements", "gold", "platinum"],
    "AS": ["pumice", "pozzolana"],
    "GU": ["fishing"],
    "MP": ["arable land", "fishing"],
    "VI": ["sun", "beaches"],
    "PR": ["none significant"],
    "UM": ["wildlife", "coral reefs"],
}

# ---------------------------------------------------------------------------
# Major exports (hardcoded, best-effort for ~160+ countries)
# ---------------------------------------------------------------------------
MAJOR_EXPORTS: dict[str, list[str]] = {
    "AF": ["opium/heroin", "fruits and nuts", "cotton", "wool", "hides and pelts", "precious and semi-precious gems"],
    "AL": ["apparel and clothing", "footwear", "asphalt", "metals and metallic ores", "crude oil", "vegetables", "fruits", "tobacco"],
    "DZ": ["petroleum", "natural gas", "petroleum products", "ammonia", "dates"],
    "AO": ["crude oil", "diamonds", "petroleum products", "coffee", "sisal", "fish"],
    "AR": ["soybeans", "soybean products", "petroleum", "cars", "corn", "wheat", "gold", "maize"],
    "AM": ["pig iron", "unwrought copper", "diamonds", "mineral products", "foodstuffs", "brandy"],
    "AU": ["iron ore", "coal", "gold", "natural gas", "beef", "aluminum", "wheat", "copper", "wool"],
    "AT": ["machinery", "motor vehicles", "paper products", "metal goods", "chemicals", "iron and steel", "textiles", "foodstuffs"],
    "AZ": ["oil and gas", "chemical products", "oilfield equipment"],
    "BS": ["crawfish", "fish", "rum", "salt", "chemicals", "fruit and vegetables"],
    "BH": ["petroleum and petroleum products", "aluminium", "textiles"],
    "BD": ["garments", "textiles", "jute and jute goods", "frozen fish and seafood", "leather"],
    "BY": ["machinery and equipment", "mineral products", "chemicals", "metals", "textiles"],
    "BE": ["chemicals", "machinery and equipment", "finished diamonds", "metals and metal products", "foodstuffs"],
    "BZ": ["sugar", "citrus", "bananas", "marine products", "crude oil", "lumber"],
    "BJ": ["cotton", "cashews", "shea butter", "textiles", "palm products"],
    "BT": ["electricity", "cardamom", "handicrafts", "cement", "calcium carbide", "copper wire", "manganese", "vegetable oil"],
    "BO": ["natural gas", "soybeans and soy products", "crude petroleum", "zinc", "tin"],
    "BA": ["metals", "clothing", "wood products", "furniture", "chemicals", "plastics"],
    "BW": ["diamonds", "copper", "nickel", "soda ash", "meat", "textiles"],
    "BR": ["transport equipment", "iron ore", "soybeans", "footwear", "coffee", "automobiles", "sugar", "orange juice"],
    "BN": ["mineral fuels", "chemical products", "crude oil"],
    "BG": ["clothing", "footwear", "iron and steel", "machinery and equipment", "fuels", "agriculture and food"],
    "BF": ["gold", "cotton", "livestock", "sesame"],
    "BI": ["coffee", "tea", "sugar", "cotton", "hides"],
    "KH": ["clothing", "timber", "rubber", "rice", "fish", "tobacco"],
    "CM": ["crude oil and petroleum products", "lumber", "cocoa beans", "aluminum", "coffee", "cotton"],
    "CA": ["motor vehicles", "machinery", "aircraft", "telecommunications equipment", "chemicals", "plastics", "fertilizers", "wood pulp", "timber", "crude petroleum", "natural gas", "electricity", "aluminum"],
    "CV": ["fuel", "shoes", "garments", "fish", "hides"],
    "CF": ["diamonds", "timber", "cotton", "coffee", "tobacco"],
    "TD": ["oil", "cotton", "cattle", "gum arabic"],
    "CL": ["copper", "lithium", "fruit", "fish products", "paper products", "chemicals", "wine"],
    "CN": ["electrical and other machinery", "data processing equipment", "apparel", "furniture", "textiles", "integrated circuits", "steel", "vehicles"],
    "CO": ["petroleum", "coal", "emeralds", "coffee", "nickel", "cut flowers", "bananas", "apparel"],
    "KM": ["vanilla", "ylang ylang", "cloves", "perfume oil", "copra"],
    "CR": ["bananas", "pineapples", "coffee", "melons", "ornamental plants", "sugar", "beef", "seafood", "electronic components", "medical equipment"],
    "HR": ["transport equipment", "machinery", "textiles", "chemicals", "foodstuffs", "fuels"],
    "CU": ["petroleum", "nickel", "medical products", "sugar", "tobacco", "fish", "citrus", "coffee"],
    "CY": ["citrus", "potatoes", "pharmaceuticals", "cement and building material", "clothing"],
    "CZ": ["machinery and transport equipment", "raw materials and fuel", "chemicals"],
    "DK": ["machinery and instruments", "meat and meat products", "pharmaceuticals", "furniture", "windmills", "dairy products"],
    "DJ": ["reexports", "hides and skins", "coffee"],
    "DM": ["bananas", "soap", "bay oil", "vegetables", "grapefruit", "oranges"],
    "DO": ["gold", "silver", "cocoa", "sugar", "coffee", "tobacco", "meats", "consumer goods"],
    "EC": ["petroleum", "bananas", "cut flowers", "shrimp", "cacao", "coffee", "wood", "fish"],
    "EG": ["crude oil and petroleum products", "cotton and textiles", "metal products", "chemicals", "processed food"],
    "SV": ["offshore assembly exports", "coffee", "textiles", "gold", "sugar", "chemicals", "electricity"],
    "GQ": ["petroleum", "methanol", "timber", "cocoa"],
    "ER": ["food and livestock", "small manufactures", "sorghum", "textiles"],
    "EE": ["machinery and electrical equipment", "wood and paper", "textiles", "food products", "furniture", "metals", "chemical products"],
    "SZ": ["soft drink concentrates", "sugar", "timber", "cotton yarn", "refrigerators", "citrus and canned fruit"],
    "ET": ["coffee", "qat", "gold", "leather products", "live animals", "oilseeds"],
    "FJ": ["sugar", "garments", "gold", "timber", "fish", "molasses", "coconut oil"],
    "FI": ["electrical and optical equipment", "machinery", "transport equipment", "paper and pulp", "chemicals", "basic metals"],
    "FR": ["machinery and transportation equipment", "aircraft", "plastics", "chemicals", "pharmaceutical products", "iron and steel", "beverages", "wine"],
    "GA": ["crude oil", "timber", "manganese", "uranium"],
    "GM": ["peanut products", "fish", "cotton lint", "palm kernels"],
    "GE": ["vehicles", "ferro-alloys", "fertilizers", "nuts", "scrap metal", "gold", "copper ores"],
    "DE": ["motor vehicles", "machinery", "chemicals", "electronic products", "electrical equipment", "pharmaceuticals", "transport equipment", "basic metals"],
    "GH": ["oil", "gold", "cocoa", "timber", "tuna", "bauxite", "aluminum", "manganese ore", "diamonds", "horticultural products"],
    "GR": ["food and beverages", "manufactured goods", "petroleum products", "chemicals", "textiles"],
    "GL": ["fish and fish products", "molybdenum ore"],
    "GD": ["nutmeg", "mace", "cocoa", "fruit and vegetables", "clothing", "mace"],
    "GT": ["sugar", "coffee", "petroleum", "apparel", "bananas", "fruits and vegetables", "cardamom"],
    "GN": ["bauxite", "gold", "diamonds", "coffee", "fish", "agricultural products"],
    "GW": ["fish", "shrimp", "cashew nuts", "peanuts", "palm kernels", "lumber"],
    "GY": ["sugar", "gold", "bauxite", "alumina", "rice", "shrimp", "molasses", "rum", "timber"],
    "HT": ["apparel", "manufactures", "oils", "cocoa", "mangoes", "coffee"],
    "HN": ["coffee", "shrimp", "bananas", "palm oil", "melon", "soap", "sugar", "textiles", "gold"],
    "HK": ["electrical machinery and appliances", "textiles", "apparel", "footwear", "watches and clocks", "toys"],
    "HU": ["machinery and equipment", "other manufactures", "food products", "raw materials", "fuels and electricity"],
    "IS": ["fish and fish products", "aluminum", "animal products", "ferrosilicon", "diatomite"],
    "IN": ["petroleum products", "precious stones", "vehicles", "machinery", "iron and steel", "chemicals", "pharmaceutical products", "cereals", "apparel", "textile yarn"],
    "ID": ["palm oil", "oil and gas", "electrical appliances", "plywood", "textiles", "rubber", "coal"],
    "IR": ["petroleum", "chemical and petrochemical products", "fruits and nuts", "carpets"],
    "IQ": ["crude oil", "crude materials excluding fuels", "food and live animals"],
    "IE": ["machinery and equipment", "computers", "chemicals", "medical devices", "pharmaceuticals", "foodstuffs", "beverages"],
    "IL": ["machinery and equipment", "software", "cut diamonds", "agricultural products", "chemicals", "defense equipment"],
    "IT": ["engineering products", "textiles and clothing", "production machinery", "motor vehicles", "transport equipment", "chemicals", "food beverages and tobacco", "minerals and nonferrous metals"],
    "JM": ["alumina", "bauxite", "sugar", "rum", "coffee", "yams", "beverages", "chemicals", "petroleum products"],
    "JP": ["motor vehicles", "semiconductors", "iron and steel products", "auto parts", "plastic materials", "power generating machinery"],
    "JO": ["textiles", "fertilizers", "potash", "phosphates", "vegetables", "pharmaceuticals"],
    "KZ": ["oil and oil products", "natural gas", "ferrous metals", "chemicals", "machinery", "grain", "wool", "meat", "coal"],
    "KE": ["tea", "horticultural products", "coffee", "petroleum products", "fish", "cement"],
    "KW": ["oil and refined products", "fertilizers"],
    "KG": ["gold", "cotton", "wool", "garments", "meat", "mercury", "uranium", "hydropower"],
    "LA": ["copper", "timber", "coffee", "electricity", "tin", "gold", "cassava"],
    "LV": ["foodstuffs", "wood and wood products", "metals", "machinery and equipment", "textiles"],
    "LB": ["jewelry", "base metals", "chemicals", "consumer goods", "fruit and vegetables", "tobacco", "construction minerals"],
    "LS": ["manufactures", "wool", "mohair", "food and live animals", "electricity", "water"],
    "LR": ["rubber", "timber", "iron ore", "diamonds", "cocoa", "coffee", "gold"],
    "LY": ["crude oil", "refined petroleum", "natural gas", "chemicals"],
    "LT": ["refined fuel", "machinery and equipment", "chemicals", "textiles", "foodstuffs", "plastics"],
    "LU": ["machinery and equipment", "steel products", "chemicals", "rubber products", "glass"],
    "MG": ["vanilla", "shellfish", "sugar", "cotton cloth", "chromite", "petroleum products"],
    "MW": ["tobacco", "tea", "sugar", "cotton", "coffee", "peanuts", "wood products"],
    "MY": ["semiconductors", "electronic equipment", "petroleum and liquefied natural gas", "palm oil", "wood and wood products", "rubber", "textiles", "chemicals"],
    "MV": ["fish", "clothing"],
    "ML": ["gold", "cotton", "livestock"],
    "MT": ["machinery and mechanical appliances", "manufactured and semi-manufactured goods", "transport equipment", "manufactures of metals"],
    "MR": ["iron ore", "fish and fish products", "gold", "copper", "petroleum"],
    "MU": ["clothing and textiles", "sugar", "cut flowers", "molasses", "fish", "precious stones"],
    "MX": ["manufactured goods", "oil and oil products", "silver", "fruits", "vegetables", "coffee", "cotton"],
    "MD": ["foodstuffs", "textiles and footwear", "machinery and mechanical appliances", "plastics and rubber", "miscellaneous manufactured articles"],
    "MN": ["copper", "apparel", "livestock", "animal products", "cashmere", "wool", "hides", "fluorspar", "other nonferrous metals", "coal"],
    "ME": ["steel", "aluminum", "agricultural products", "consumer goods", "tourism services"],
    "MA": ["clothing and textiles", "electric components", "inorganic chemicals", "transistors", "crude minerals", "fertilizers", "petroleum products", "citrus fruits", "vegetables", "fish"],
    "MZ": ["aluminum", "prawns", "cashews", "cotton", "sugar", "citrus", "timber", "bulk electricity"],
    "MM": ["natural gas", "wood products", "pulses", "beans", "fish", "rice", "clothing", "jade and gems"],
    "NA": ["diamonds", "copper", "gold", "zinc", "lead", "uranium", "cattle", "white fish and mollusks"],
    "NP": ["clothing", "pulses", "carpet", "textiles", "juice", "pashmina fiber", "hides"],
    "NL": ["machinery and equipment", "chemicals", "petroleum products", "finished diamonds"],
    "NZ": ["dairy products", "meat", "wood and wood products", "fish", "machinery"],
    "NI": ["coffee", "beef", "gold", "sugar", "peanuts", "shrimp and lobster", "tobacco"],
    "NE": ["uranium ore", "livestock", "cowpeas", "onions"],
    "NG": ["petroleum and petroleum products", "cocoa", "rubber"],
    "KP": ["minerals", "metallurgical products", "manufactures including armaments", "textiles", "agricultural and fishery products"],
    "NO": ["petroleum and petroleum products", "machinery and equipment", "metals", "chemicals", "ships", "fish"],
    "OM": ["petroleum", "copper", "asbestos", "marble", "limestone"],
    "PK": ["textiles", "clothing", "rice", "leather goods", "sporting goods", "chemicals", "manufactures", "carpets and rugs"],
    "PA": ["gold", "bananas", "shrimp", "sugar", "iron or steel waste", "pineapples", "watermelons"],
    "PG": ["oil", "gold", "copper ore", "logs", "palm oil", "coffee", "cocoa", "crayfish", "prawn"],
    "PY": ["soybeans", "livestock feed", "cotton", "meat", "edible oils", "wood", "leather", "gold"],
    "PE": ["copper", "gold", "zinc", "crude petroleum and byproducts", "lead", "coffee", "asparagus", "artichokes", "paprika", "sugar", "cotton"],
    "PH": ["semiconductors and electronic products", "transport equipment", "garments", "copper products", "petroleum products", "coconut oil", "fruits"],
    "PL": ["machinery and transport equipment", "intermediate manufactured goods", "miscellaneous manufactured goods", "food and live animals"],
    "PT": ["motor vehicles and parts", "agricultural machinery", "electrical equipment", "footwear", "clothing", "fuel", "cork and paper products", "hides"],
    "QA": ["liquefied natural gas", "petroleum products", "fertilizers", "steel", "polymers"],
    "RO": ["machinery and equipment", "metals and metal products", "mineral products and fuels"],
    "RU": ["petroleum and petroleum products", "natural gas", "metals", "wood and wood products", "chemicals", "civilian and military manufactures", "wheat", "arms"],
    "RW": ["coffee", "tea", "hides", "tin ore", "pyrethrum", "wolfram ore"],
    "SA": ["petroleum and petroleum products", "basic chemicals"],
    "SN": ["fish", "groundnuts", "petroleum products", "phosphates", "cotton"],
    "RS": ["iron and steel", "rubber", "clothes", "wheat", "fruit and vegetables", "nonferrous metals", "electric appliances"],
    "SC": ["fish", "cinnamon bark", "copra", "petroleum products re-exports"],
    "SL": ["diamonds", "rutile", "cocoa", "coffee", "fish"],
    "SG": ["machinery and equipment", "consumer electronics", "pharmaceuticals", "other chemicals", "mineral fuels"],
    "SK": ["vehicles", "electrical equipment", "mechanical appliances", "metals and metal articles"],
    "SI": ["manufactured goods", "machinery and transport equipment", "chemicals", "food"],
    "SB": ["timber", "fish", "copra", "palm oil", "cocoa", "coconut oil"],
    "SO": ["livestock", "bananas", "hides", "fish", "charcoal", "scrap metal"],
    "ZA": ["gold", "diamonds", "platinum", "other metals and minerals", "machinery and equipment"],
    "SS": ["oil", "livestock", "sorghum", "gum arabic", "sesame"],
    "ES": ["machinery", "motor vehicles", "foodstuffs and beverages including wine", "pharmaceuticals"],
    "LK": ["textiles and apparel", "tea and spices", "rubber and rubber-based products", "precious stones", "coconut products", "fish"],
    "SD": ["oil", "cotton", "sesame", "livestock", "groundnuts", "gum arabic", "sugar"],
    "SR": ["gold", "oil", "lumber", "fish and fish products", "shrimp", "rice", "bananas"],
    "SE": ["machinery", "motor vehicles", "paper products", "pulp and wood", "iron and steel products", "chemicals"],
    "CH": ["machinery", "chemicals", "metals", "watches", "agricultural products", "pharmaceuticals"],
    "SY": ["crude oil", "minerals", "petroleum products", "fruits and vegetables", "cotton fiber", "clothing", "meat and live animals"],
    "TW": ["semiconductors", "petrochemicals", "automobile parts", "ships", "wireless communication equipment", "flat display displays", "steel", "electronics", "plastics", "computers"],
    "TJ": ["aluminum", "electricity", "cotton", "fruits", "vegetable oil"],
    "TZ": ["gold", "coffee", "cashew nuts", "manufactures", "cotton"],
    "TH": ["vehicles and parts", "computers", "jewelry", "polymers of ethylene", "refined fuels", "electronics", "fish products", "rubber", "sugar", "rice"],
    "TL": ["oil", "coffee", "sandalwood", "marble"],
    "TG": ["reexports", "cotton", "phosphates", "coffee", "cocoa"],
    "TO": ["squash", "fish", "vanilla beans", "root crops"],
    "TT": ["petroleum and petroleum products", "liquefied natural gas", "methanol", "ammonia", "urea", "steel products", "beverages"],
    "TN": ["clothing and accessories", "electrical equipment", "petroleum products", "phosphates and chemicals", "agricultural products", "seafood"],
    "TR": ["motor vehicles", "ships and boats", "machinery", "iron and steel", "textile and raw materials", "food products"],
    "TM": ["gas", "crude oil", "petrochemicals", "textiles", "cotton fiber"],
    "UG": ["coffee", "fish and fish products", "tea", "cotton", "flowers", "horticultural products", "gold"],
    "UA": ["ferrous and nonferrous metals", "fuel and petroleum products", "chemicals", "machinery and transport equipment", "food products"],
    "AE": ["crude oil", "natural gas", "re-exports", "dried fish", "dates"],
    "GB": ["manufactured goods", "fuels", "chemicals", "food beverages and tobacco", "machinery"],
    "US": ["aircraft and spacecraft", "motor vehicles and parts", "semiconductors", "pharmaceutical preparations", "industrial machinery", "petroleum products", "soybeans", "medical instruments"],
    "UY": ["beef", "soybeans", "cellulose", "rice", "wheat", "wood", "dairy products", "wool"],
    "UZ": ["energy products", "cotton", "gold", "mineral fertilizers", "ferrous and nonferrous metals", "textiles", "food products", "machinery and equipment"],
    "VU": ["copra", "beef", "cocoa", "timber", "kava", "coffee"],
    "VE": ["petroleum and petroleum products", "bauxite and aluminum", "minerals", "chemicals", "agricultural products"],
    "VN": ["clothes", "footwear", "electronics", "seafood", "crude oil", "machinery", "wooden products", "rice", "machinery"],
    "WS": ["fish", "coconut oil and cream", "copra", "taro", "automotive parts", "garments", "beer"],
    "YE": ["crude oil", "coffee", "dried and salted fish", "liquefied natural gas"],
    "ZM": ["copper and cobalt", "cobalt", "electricity", "tobacco", "flowers", "cotton"],
    "ZW": ["platinum", "cotton", "tobacco", "gold", "ferroalloys", "textiles and clothing"],
    "KZ": ["oil and oil products", "ferrous metals", "chemicals", "machinery", "grain", "wool"],
    "MK": ["food", "beverages and tobacco", "miscellaneous manufactures", "iron and steel", "chromium"],
    "XK": ["mining and processed metal products", "scrap metals", "leather products", "machinery", "appliances", "prepared foodstuffs beverages and tobacco"],
    "KI": ["fish", "coconut products"],
    "PW": ["shellfish", "tuna", "copra", "garments"],
    "MH": ["coconut products", "fish"],
    "FM": ["fish", "garments", "bananas", "black pepper"],
    "NR": ["phosphates"],
    "TV": ["fish"],
    "CK": ["copra", "papayas", "fresh and canned citrus fruit", "coffee"],
    "NU": ["canned coconut cream", "copra", "honey", "vanilla", "passion fruit products"],
    "WF": ["copra", "handicrafts", "fish"],
    "TK": ["stamps", "copra", "handicrafts"],
    "NC": ["ferronickel", "nickel ore", "fish"],
    "PF": ["cultured black pearls", "coconut products", "mother of pearl", "vanilla", "shark meat"],
    "GF": ["shrimp", "timber", "gold", "rum", "rosewood"],
    "GP": ["bananas", "sugar", "rum", "vegetables"],
    "MQ": ["refined petroleum products", "bananas", "rum", "pineapples"],
    "RE": ["sugar", "rum", "molasses", "vanilla", "tea", "tobacco"],
    "YT": ["fish and fish products"],
    "PM": ["fish and fish products"],
    "BL": ["fish"],
    "MF": ["none significant"],
    "SX": ["none significant"],
    "CW": ["petroleum products", "live animals and animal products"],
    "BQ": ["none significant"],
    "AW": ["transport equipment", "live animals and animal products", "art and collectibles"],
    "MS": ["electronic components", "plastic bags", "apparel", "hot peppers", "limes", "livestock"],
    "KY": ["turtle products", "finished goods", "re-exports"],
    "AI": ["lobster", "fish", "livestock", "salt", "concrete blocks", "rum"],
    "VG": ["rum", "fresh fish", "fruits and animals", "gravel", "sand"],
    "BM": ["re-exports of pharmaceuticals"],
    "TC": ["lobster", "dried and fresh conch", "conch shells"],
    "GI": ["petroleum", "manufactures"],
    "JE": ["financial services", "tourism"],
    "GG": ["financial services", "tourism"],
    "IM": ["tweeds", "herring", "processed shellfish", "beef", "lamb"],
    "FK": ["wool", "hides", "meat"],
    "FO": ["fish and fish products", "ships"],
    "SJ": ["fish", "coal"],
    "IO": ["none — military use only"],
    "HM": ["none significant"],
    "BV": ["none significant"],
    "GS": ["none significant"],
    "AQ": ["none — research only"],
    "CX": ["none significant"],
    "CC": ["coconuts and coconut products"],
    "NF": ["tourism", "postage stamps"],
    "PN": ["none significant"],
    "TF": ["none significant"],
    "UM": ["none significant"],
    "VA": ["none significant"],
    "SM": ["building stone", "lime", "wood", "chestnuts", "wheat", "wine", "baked goods", "hides"],
    "AD": ["tobacco products", "furniture", "chemicals", "fine arts"],
    "MC": ["chemicals", "rubber and plastics", "household goods"],
    "LI": ["small specialty machinery", "dental products", "stamps", "hardware"],
    "GI": ["petroleum", "manufactures"],
    "VI": ["rum", "bay rum", "arrowroot starch", "vegetables"],
    "PR": ["pharmaceuticals", "electronics", "apparel", "canned tuna", "rum"],
    "GU": ["transshipments of refined petroleum products", "construction materials", "fish"],
    "AS": ["canned tuna"],
    "MP": ["garments"],
}

# ---------------------------------------------------------------------------
# Income level fetcher
# ---------------------------------------------------------------------------

def _fetch_world_bank_income() -> dict[str, str | None]:
    """Return {iso2_code: income_level_str} from World Bank API."""
    log.info("Fetching income levels from World Bank API...")
    try:
        resp = requests.get(WORLD_BANK_URL, timeout=30)
        resp.raise_for_status()
        data = resp.json()
        # data[0] = metadata, data[1] = list of country objects
        countries_raw = data[1] if len(data) > 1 else []
        result = {}
        for item in countries_raw:
            code = item.get("iso2Code", "").upper()  # 2-letter ISO, matches our DB
            income_raw = item.get("incomeLevel", {}).get("value", "")
            income_mapped = _INCOME_MAP.get(income_raw)
            if code:
                result[code] = income_mapped
        log.info("World Bank returned %d countries", len(result))
        return result
    except Exception as exc:
        log.warning("World Bank API failed (%s) — income_level will be skipped", exc)
        return {}


# ---------------------------------------------------------------------------
# Main seeder
# ---------------------------------------------------------------------------

def seed_country_extras(db: Session) -> int:
    """
    Update income_level, natural_resources, major_exports, credit_rating_sp
    for all countries in the DB.  Returns count of rows updated.
    """
    wb_income = _fetch_world_bank_income()

    # Gather all codes currently in DB
    rows = db.execute(
        Country.__table__.select().with_only_columns(
            Country.__table__.c.code,
            Country.__table__.c.id,
        )
    ).fetchall()

    if not rows:
        log.warning("No countries found in DB — run the countries seeder first.")
        return 0

    updated = 0
    for row in rows:
        code = row.code
        updates: dict = {}

        income = wb_income.get(code)
        # Some WB codes are 3-letter; also try uppercase just in case
        if income is None and code in wb_income:
            income = wb_income[code]
        updates["income_level"] = income

        if code in NATURAL_RESOURCES:
            updates["natural_resources"] = NATURAL_RESOURCES[code]

        if code in MAJOR_EXPORTS:
            updates["major_exports"] = MAJOR_EXPORTS[code]

        if code in CREDIT_RATINGS_SP:
            updates["credit_rating_sp"] = CREDIT_RATINGS_SP[code]

        if updates:
            db.execute(
                Country.__table__.update()
                .where(Country.__table__.c.code == code)
                .values(**updates)
            )
            updated += 1

    db.commit()
    log.info("Updated %d / %d countries", updated, len(rows))
    return updated


def run() -> None:
    db = SessionLocal()
    try:
        count = seed_country_extras(db)
        print(f"country_extras seeder complete — {count} countries updated.")
    finally:
        db.close()


if __name__ == "__main__":
    run()
