import sentry_sdk
from fastapi import FastAPI, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from prometheus_fastapi_instrumentator import Instrumentator
from sentry_sdk.integrations.fastapi import FastApiIntegration
from sentry_sdk.integrations.starlette import StarletteIntegration
from slowapi import _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded

from app.config import settings
from app.limiter import limiter
from app.routers import health, countries, assets, trade, auth, search, feed, admin, share, og, sitemap, snapshots
from app.routers import alerts as alerts_router
from app.routers import telegram_webhook
from app.routers.admin import public_router as blog_router, track_router
from app.routers import intelligence
from app.routers import feedback
from app.routers import rates as rates_router
from app.routers import earnings as earnings_router
from app.routers import newsletter
from app.routers import screener as screener_router
from app.routers import news as news_router
from app.routers import blocs as blocs_router
from app.routers import email_alerts as email_alerts_router

if settings.sentry_dsn:
    sentry_sdk.init(
        dsn=settings.sentry_dsn,
        integrations=[StarletteIntegration(), FastApiIntegration()],
        traces_sample_rate=0.2,   # 20% of requests traced (adjust up if needed)
        send_default_pii=False,
        environment="production" if not settings.debug else "development",
    )

app = FastAPI(
    title="MetricsHour API",
    description="Global financial intelligence — stocks, macro, trade, crypto, FX, commodities",
    version="0.1.0",
    # Disable interactive docs in production to avoid exposing the full API schema
    docs_url=None if not settings.debug else "/docs",
    redoc_url=None if not settings.debug else "/redoc",
    openapi_url=None if not settings.debug else "/openapi.json",
)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.allowed_origins,
    allow_methods=["GET", "POST", "PUT", "DELETE"],
    allow_headers=["Authorization", "Content-Type"],
)


@app.middleware("http")
async def security_headers(request: Request, call_next) -> Response:
    response = await call_next(request)
    # Security headers are set by Nginx (security-headers.conf) — no duplication here.

    # Edge cache (Cloudflare CDN, free — no KV writes).
    # TTLs match data freshness; auth/feed/alerts are private and never cached.
    path = request.url.path
    if request.method == "GET" and response.status_code == 200:
        if path.startswith("/snapshots/"):
            # R2 snapshots regenerated daily at 7am — 1hr edge cache, 24hr stale fallback
            cc = "public, s-maxage=3600, stale-while-revalidate=86400"
        elif path.startswith("/api/trade/"):
            # Bilateral trade data is annual — cache 6 hours at edge
            cc = "public, s-maxage=21600, stale-while-revalidate=3600"
        elif path.startswith("/api/trade"):
            # Trade pair list — top 100, changes annually
            cc = "public, s-maxage=3600, stale-while-revalidate=300"
        elif path.startswith("/api/countries/") and path.endswith("/trade-partners"):
            cc = "public, s-maxage=3600, stale-while-revalidate=300"
        elif path.startswith("/api/countries"):
            # Country list + detail — changes monthly at most
            cc = "public, s-maxage=3600, stale-while-revalidate=300"
        elif path.endswith("/prices"):
            # Price history — updated by Celery every 15min, don't over-cache
            cc = "public, s-maxage=60, stale-while-revalidate=30"
        elif path.startswith("/og/china/"):
            # China stock OG images — daily prices
            cc = "public, s-maxage=86400, stale-while-revalidate=3600"
        elif path.startswith("/api/assets/"):
            # Asset detail — prices update every 15min
            cc = "public, s-maxage=900, stale-while-revalidate=60"
        elif path.startswith("/api/assets"):
            # Asset list — prices update every 15min
            cc = "public, s-maxage=300, stale-while-revalidate=60"
        elif path.startswith("/api/summaries/"):
            # Page summaries/insights — regenerated by Celery insight batches every 2-6h
            cc = "public, s-maxage=3600, stale-while-revalidate=7200"
        elif path.startswith("/api/intelligence/"):
            # Spotlight rotates every 3h — 1hr edge cache is safe
            cc = "public, s-maxage=3600, stale-while-revalidate=3600"
        elif path.startswith("/api/feed"):
            # Feed events generated every 3min by Celery
            cc = "public, s-maxage=180, stale-while-revalidate=60"
        elif path.startswith("/api/blog/"):
            # Blog posts change when published — 1hr edge cache
            cc = "public, s-maxage=3600, stale-while-revalidate=3600"
        elif path.startswith("/api/search"):
            cc = "public, s-maxage=300, stale-while-revalidate=60"
        elif path.startswith("/og/"):
            # OG images change at most once a day
            cc = "public, s-maxage=86400, stale-while-revalidate=3600"
        else:
            cc = None
        if cc:
            response.headers["Cache-Control"] = cc

    return response

app.include_router(health.router)
app.include_router(countries.router, prefix="/api")
app.include_router(assets.router, prefix="/api")
app.include_router(trade.router, prefix="/api")
app.include_router(auth.router, prefix="/api")
app.include_router(search.router, prefix="/api")
app.include_router(feed.router, prefix="/api")
app.include_router(admin.router, prefix="/api")
app.include_router(blog_router, prefix="/api")
app.include_router(intelligence.router, prefix="/api")
app.include_router(feedback.router)
app.include_router(share.router)   # /s/{id} — social share OG preview (no prefix)
app.include_router(og.router)      # /og/feed/{id}.png, /og/countries/{code}.png, /og/stocks/{symbol}.png
app.include_router(sitemap.router) # /sitemap.xml — no Bot Fight Mode here
app.include_router(alerts_router.router, prefix="/api")
app.include_router(telegram_webhook.router)  # social draft helpers (no routes — logic called from alerts webhook)
app.include_router(track_router)   # POST /api/track — page view analytics
app.include_router(snapshots.router)  # GET /snapshots/{key} — R2 CDN proxy, CF-cached at edge
app.include_router(newsletter.router, prefix="/api")  # POST /api/newsletter/subscribe, GET /api/newsletter/unsubscribe
app.include_router(rates_router.router, prefix="/api")  # GET /api/rates/, /api/rates/yield-curve, /api/rates/{series_id}
app.include_router(earnings_router.router, prefix="/api")  # GET /api/earnings/upcoming, /api/earnings/recent
app.include_router(screener_router.router, prefix="/api")  # GET /api/screener, /api/screener/sectors
app.include_router(news_router.router, prefix="/api")     # GET /api/news/{symbol} — Tiingo news
app.include_router(blocs_router.router, prefix="/api")  # GET /api/blocs/, /api/blocs/{slug}
app.include_router(email_alerts_router.router, prefix="/api")  # POST /api/email-alerts (no auth required)


Instrumentator().instrument(app).expose(app, endpoint="/metrics", include_in_schema=False)


@app.get("/")
def root() -> dict:
    return {"name": "MetricsHour API", "docs": "/docs"}
