/**
 * MetricsHour API Cache Worker
 *
 * Caching strategy:
 *   - API responses: CF Cache API (caches.default) — free, no quotas, per-datacenter
 *   - OG images:     R2 direct serve — zero origin hit, global CDN
 *   - KV:            Reserved for spotlight/intelligence (globally consistent hot data)
 *
 * CF Cache API vs KV:
 *   KV: 100k reads/day + 1k writes/day (free tier) — use for globally-consistent hot keys
 *   Cache API: unlimited, URL-keyed, per-datacenter — ideal for API response caching
 *
 * Deploy: wrangler deploy
 * DNS: api.metricshour.com → Worker (orange cloud in Cloudflare dashboard)
 */

// TTL per route pattern (seconds). Cache-Control max-age drives CF edge eviction.
// IMPORTANT: all regexes are case-insensitive (i flag) — frontend sends lowercase paths.
const CACHE_RULES = [
  // Country detail + sub-routes (1h — updates daily via Celery)
  { re: /^\/api\/countries\/[a-z]{2,3}$/i,                         ttl: 3600 },
  { re: /^\/api\/countries\/[a-z]{2,3}\/trade-partners$/i,         ttl: 3600 },
  { re: /^\/api\/countries\/[a-z]{2,3}\/gdp-history$/i,            ttl: 86400 },
  { re: /^\/api\/countries\/[a-z]{2,3}\/timeseries/i,              ttl: 86400 },
  { re: /^\/api\/countries\/[a-z]{2,3}\/stocks$/i,                 ttl: 3600 },
  { re: /^\/api\/countries$/i,                                      ttl: 300 },

  // Asset / stock detail (15m — price worker runs every 15m)
  { re: /^\/api\/assets\/[a-z0-9.\-]+$/i,                          ttl: 900 },
  { re: /^\/api\/assets$/i,                                        ttl: 300 },

  // Trade pair detail (24h — data updates annually)
  { re: /^\/api\/trade\/[a-z]{2,3}\/[a-z]{2,3}$/i,                ttl: 86400 },

  // Summaries (1h — regenerated by Celery daily at 2am)
  { re: /^\/api\/summaries\/[a-z]+\/.+$/i,                         ttl: 3600 },

  // Insights (1h — generated on demand, cached)
  { re: /^\/api\/insights\/[a-z]+\/.+$/i,                          ttl: 3600 },

  // Intelligence spotlight (3h — matches Celery refresh_spotlight interval)
  { re: /^\/api\/intelligence\/spotlight$/i,                        ttl: 10800 },

  // Feed listing (1m — live feed, short TTL)
  { re: /^\/api\/feed$/i,                                          ttl: 60 },

  // Individual feed events (24h — immutable once created)
  { re: /^\/api\/feed\/events\/\d+$/i,                             ttl: 86400 },

  // Blog posts (1h — content rarely changes)
  { re: /^\/api\/blog\/[a-z0-9\-]+$/i,                             ttl: 3600 },
]

// KV-served routes: globally consistent, written by backend workers on data updates
const KV_RULES = [
  { re: /^\/api\/intelligence\/spotlight$/, key: 'spotlight' },
]

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)

    // ── CORS preflight ────────────────────────────────────────────────────────
    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: corsHeaders() })
    }

    // ── /og/* — serve PNG images directly from R2 (zero origin hit) ─────────
    if (request.method === 'GET' && url.pathname.startsWith('/og/')) {
      const key = url.pathname.slice(1)  // /og/countries/US.png → og/countries/US.png
      const obj = await env.R2.get(key)
      if (obj) {
        return new Response(obj.body, {
          headers: {
            'Content-Type': 'image/png',
            'Cache-Control': 'public, max-age=86400',
            'X-Served-From': 'R2',
            ...corsHeaders(),
          },
        })
      }
      return forwardToOrigin(request, env)
    }

    // Only cache GET requests
    if (request.method !== 'GET') {
      return forwardToOrigin(request, env)
    }

    const rule = CACHE_RULES.find(r => r.re.test(url.pathname))
    if (!rule) {
      return forwardToOrigin(request, env)
    }

    // ── CF Cache API — check first (free, per-datacenter, no quota) ───────────
    const cache = caches.default
    const cacheRequest = new Request(url.toString(), { method: 'GET' })

    const cfCached = await cache.match(cacheRequest)
    if (cfCached) {
      const body = await cfCached.text()
      return jsonResponse(body, 'HIT', rule.ttl)
    }

    // ── KV-served routes — only on CF Cache miss (globally consistent) ────────
    // KV is checked AFTER CF Cache to avoid burning KV reads on every request.
    // Free tier: 100k reads/day — CF Cache absorbs the vast majority.
    const kvRule = KV_RULES.find(r => r.re.test(url.pathname))
    if (kvRule) {
      const kvData = await env.API_CACHE.get(kvRule.key)
      if (kvData !== null) {
        // Warm CF Cache so subsequent requests in this datacenter skip KV
        ctx.waitUntil(
          cache.put(
            cacheRequest,
            new Response(kvData, {
              headers: {
                'Content-Type': 'application/json',
                'Cache-Control': `public, max-age=${rule.ttl}`,
              },
            })
          )
        )
        return jsonResponse(kvData, 'KV-HIT', rule.ttl)
      }
    }

    // ── Origin fetch ──────────────────────────────────────────────────────────
    const originResp = await forwardToOrigin(request, env)
    if (!originResp.ok) return addCors(originResp)

    const body = await originResp.text()

    // Store in CF Cache async (don't block response)
    ctx.waitUntil(
      cache.put(
        cacheRequest,
        new Response(body, {
          headers: {
            'Content-Type': 'application/json',
            'Cache-Control': `public, max-age=${rule.ttl}`,
          },
        })
      )
    )

    return jsonResponse(body, 'MISS', rule.ttl)
  },
}

function forwardToOrigin(request, env) {
  const url = new URL(request.url)
  const originUrl = env.ORIGIN + url.pathname + url.search
  return fetch(originUrl, {
    method: request.method,
    headers: Object.fromEntries(request.headers),
    body: request.body,
    // Pass 3xx responses back to the browser unchanged instead of following them.
    // Without this, fetch() follows 307s from the origin (e.g. Google OAuth
    // authorize → accounts.google.com), serving the redirect target's HTML at
    // api.metricshour.com — which breaks OAuth because the browser never
    // navigates to accounts.google.com and can't see its own Google cookies.
    redirect: 'manual',
    // resolveOverride: connect directly to the origin IP, bypass CF proxy loop,
    // but use api.metricshour.com as SNI so the Let's Encrypt cert validates.
    cf: { resolveOverride: env.ORIGIN_IP },
  })
}

function corsHeaders() {
  return {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  }
}

function securityHeaders() {
  return {
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'DENY',
    'X-XSS-Protection': '1; mode=block',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
    'Content-Security-Policy': "default-src 'none'; frame-ancestors 'none'",
  }
}

function jsonResponse(body, cacheStatus, ttl = 60) {
  return new Response(body, {
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': `public, max-age=${ttl}`,
      'X-Cache': cacheStatus,
      ...corsHeaders(),
      ...securityHeaders(),
    },
  })
}

function addCors(response) {
  const r = new Response(response.body, response)
  Object.entries({ ...corsHeaders(), ...securityHeaders() }).forEach(([k, v]) => r.headers.set(k, v))
  return r
}
