name = "metricshour-api-cache"
main = "src/index.js"
compatibility_date = "2024-11-01"

# Bind the KV namespace created in the Cloudflare dashboard
# Dashboard → Workers & Pages → KV → metricshour-api-cache
[[kv_namespaces]]
binding = "API_CACHE"
id = "f58822613dbd46e6b044b5ae8d5553aa"





[vars]
ORIGIN = "https://89.167.35.114"

[[routes]]
pattern = "api.metricshour.com/*"
zone_name = "metricshour.com"
